// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llivfuamsugcbipladgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsaXZmdWFtc3VnY2JpcGxhZGdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2ODEzNzQsImV4cCI6MjA5MTI1NzM3NH0.gC0Vp9L9Iyk_5qLj1V7GPkhxWSiCBqMNnK6-cRuPz7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});